### ISSUE TITLE
后台要怎么在本地运行呢

### ISSUE THREAD

**Issue by scjjjiejie** [hai-27/store-server#1]

**Comment by hai-27** [comment]
1. 首先你的本地需要有node.js执行环境、npm和Mysql数据库。
2. clone项目到本地。
3. 进入项目目录（cd store-server）。
4. 安装依赖（npm install）。
5. 运行项目node app.js。
6. 建议安装nodemon，支持热更新（npm i -g nodemon），安装后可以使用nodemon app.js运行项目，个人建议。
7. 需要自行建库建表，根目录的storeDB.sql有建库建表sql语句。
8. 需要自行插入数据到数据库，根目录的analogDataSql.sql有虚拟数据插入语句。
9. 根据你本地数据库连接的相关设置修改根目录config.js中关于数据库连接的配置。
10. 如果想前端连接你本地的后端，需要修改前端根目录的vue.config.js后端地址。

**Comment by zdy3306** [comment]
没有上传图片的功能吗

**Comment by G-xiaofeng** [comment]
analogDataSql.sql里面只有插入数据的代码,,没有建库和建表的代码

> 1. 首先你的本地需要有node.js执行环境、npm和Mysql数据库。
> 2. clone项目到本地。
> 3. 进入项目目录（cd store-server）。
> 4. 安装依赖（npm install）。
> 5. 运行项目node app.js。
> 6. 建议安装nodemon，支持热更新（npm i -g nodemon），安装后可以使用nodemon app.js运行项目，个人建议。
> 7. 需要自行建库建表，根目录的storeDB.sql有建库建表sql语句。
> 8. 需要自行插入数据到数据库，根目录的analogDataSql.sql有虚拟数据插入语句。
> 9. 根据你本地数据库连接的相关设置修改根目录config.js中关于数据库连接的配置。
> 10. 如果想前端连接你本地的后端，需要修改前端根目录的vue.config.js后端地址。

**Comment by G-xiaofeng** [comment]
analogDataSql.sql里面只有插入数据的代码,没有建库和建表的代码,有没有完整的啊

**Comment by hai-27** [comment]
@G-xiaofeng 建库建表的语句在[storeDB.sql](https://github.com/hai-27/store-server/blob/master/storeDB.sql)

**Comment by liuchanghaojh** [comment]
analogDataSql.sql插入数据时找不到图片的路径怎么解决呀

**Comment by liuchanghaojh** [comment]
如何实现PC端和移动端自适应屏幕宽度呢

**Comment by seraphzxz** [comment]
执行 node app.js 启动项目报错：
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './app/middleware/rewriteUrl'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/seraphzxz/jobs/projects/app_store/store-server-master/app.js:21:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
